import Head from 'next/head'
import React, {useCallback, useEffect, useState} from "react";
import HomeLayout from "@/components/layouts/Home";
import {useRouter} from "next/router";
import {Button} from "flowbite-react";
import Modal from '@/components/Modal';


interface Event {
    name: string;
    description: string;
    id: string;
    date: string;
    time: string;
    company:Company
}

interface User{
  
    name : string;
    firstname:string;
}

interface Profile{
    profiles : User;
}

interface Company{
    address : string;
    city : string;
    zipcode : string;
}





export default function Event() {
    const [event, setEvent] = useState<Event[]>([]);
    const [users, setUsers] = useState<Profile[]>([]);
    const [deleteModal, setDeleteModal] = useState<boolean>(false);
    const [isDelete, setIsDelete] = useState<boolean>(false);
    const [idEvent, setIdEvent] = useState<string>('');
    const [error, setError] = useState("");
    const router = useRouter();

    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
    },[]);


    useEffect(() => {
        if (!router.isReady) return;

        const {id} = router.query;
        if (typeof id === 'string') {
            setIdEvent(id)

            fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/event/${id}`, {
                method: 'GET',
            })
                .then(response => response.json())
                .then((data) => {
                   
                    setEvent(data)
                }).catch((error) => {
                console.log(error);

            });
        }
    }, [router.isReady]);


    useEffect( () => {

        if (!router.isReady) return;
        const {id} = router.query;
        fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/event/getUsersByEvent/${id}`, {
            method: 'GET',
        })
            .then(response => response.json())
            .then((data) => {
                setUsers(data)
            }).catch((error) => {
            console.log(error);

        });

    }, [router.isReady]);


    const deleteEvent = useCallback(async (e: any) => {
        e.preventDefault();

        await fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/event/${idEvent}`, {
            method: 'DELETE',   
        })
            .then(response => response.json())
            .then((data) => {
                router.push('/me/event');
            }).catch((error) => {
                console.log(error);
            });
    }, [idEvent]);

    
    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HomeLayout>
                <section>
                    <div className="container mx-auto pt-10 h-screen">
                     
                            <div className="grid grid-cols-1 md:grid-cols-12 h-4/6">
                                <div className="md:col-span-5 my-10">
                                    <div className="py-8 px-10 mx-auto  max-w-4xl rounded-lg lg:py-14 bg-white">
                                        <h2 className="mb-3 text-xl font-bold text-gray-900">Les Ludotters</h2>
                                        <hr></hr>

                                        {
                                            users.map((user, index) => (
                                                <div key={index} className="w-full mt-5 font-medium rounded px-5 py-2 bg-custom-highlight-orange">
                                                    {user.profiles.firstname} {user.profiles.name}
                                                </div>
                                            )
                                        )}
                                       
                                    </div>
                                </div>
                                <div className="md:col-span-7 md:col-start-7 my-10">

                                    <div className="py-8 px-10 mx-auto  max-w-4xl rounded-lg lg:py-14 bg-white">

                                        <h2 className="mb-10 text-xl font-bold text-gray-900">{event[0]?.name}</h2>
                                        <div className="flex mb-5 justify-between">
                                            <span className="bg-custom-pastel-purple rounded font-medium px-3 py-1 leading-[100%] inline-block">Où ?</span>
                                            <span className="px-3 py-1 leading-[100%] inline-block">{event[0]?.company.address} {event[0]?.company.city} {event[0]?.company.zipcode}</span>
                                        </div>
                                        <div className="flex mb-5 justify-between">
                                            <span className="bg-custom-highlight-orange rounded font-medium px-3 py-1 leading-[100%] inline-block">Quand ?</span>
                                            <span className="px-3 py-1 leading-[100%] inline-block">{event[0]?.date} {event[0]?.time}</span>
                                        </div>
                                        <div className="flex mb-5 justify-between ">
                                            <span className="bg-custom-pastel-blue rounded font-medium px-3 py-1 leading-[100%] inline-block">Pour quoi ?</span>
                                            <span className="px-3 py-1 leading-[100%] inline-block">{event[0]?.description} </span>
                                        </div>

                                        <div className="mt-10 flex">
                                       
                                            <button onClick={() => setDeleteModal(true)} className="px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-white bg-custom-orange rounded-lg hover:bg-custom-hover-orange">
                                                Annuler l'évènement
                                            </button>
                                            <button className="mx-2 px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-white bg-custom-orange rounded-lg hover:bg-custom-hover-orange">
                                                Modifier l'évènement
                                            </button>
                                        </div>

                            

                                    </div>

                                  
                    
                                    {deleteModal ? (
                                    <>
                                    <Modal setShowModal={setDeleteModal} title="">
                                    <div className="text-center">
                                               
                                        <h3 className="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">
                                            Voulez-vous vraiment annuler cet évènement ?
                                        </h3>

                                        <div className="flex justify-center gap-4">
                                            <Button color="failure" onClick={deleteEvent}>
                                                Oui, je suis sûr
                                            </Button>
                                            <Button
                                                color="gray"
                                                onClick={() => setDeleteModal(false)}
                                            >
                                                Non, annuler
                                            </Button>
                                        </div>
                                    </div>

                                    </Modal>
                                    </>
                                    ) : null}
                                 
                                </div> 
                            </div>
                    
                    </div>
                </section>
            </HomeLayout>
        </>
    )
}