import Head from 'next/head'
import React, { useEffect } from "react";
import HomeLayout from "@/components/layouts/Home";
import FormCreate from "@/components/event/FormCreate";


export default function Event() {
    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
    });



    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeLayout>
                <section>

                    
                    <div className="py-8 px-10 mx-auto my-24 max-w-4xl rounded-lg lg:py-16 bg-white">

                        <h2 className="mb-10 text-xl font-bold text-gray-900">Soirée</h2>
                        <div className="flex mb-5 justify-between">
                            <span className="bg-custom-pastel-purple rounded font-medium px-3 py-1 leading-[100%] inline-block">Où ?</span>
                            <span className="px-3 py-1 leading-[100%] inline-block">12344</span>
                        </div>
                        <div className="flex mb-5 justify-between">
                            <span className="bg-custom-highlight-orange rounded font-medium px-3 py-1 leading-[100%] inline-block">Quand ?</span>
                            <span className="px-3 py-1 leading-[100%] inline-block">12344</span>
                        </div>
                        <div className="flex mb-5 justify-between ">
                            <span className="bg-custom-pastel-blue rounded font-medium px-3 py-1 leading-[100%] inline-block">Pour quoi ?</span>
                            <span className="px-3 py-1 leading-[100%] inline-block">12344</span>
                        </div>

                        <form className="mt-20">
                        <div className="mb-5">
                            <div className=" flex justify-between items-center">
                                <label htmlFor="name"
                                    className="block mb-2 text-sm font-medium text-gray-900">Nombre de joueurs</label>
                                <input type="number" name="name" id="name"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-custom-pastel-purple focus:border-custom-pastel-purple focus:bg-white block  p-2.5"
                                   required/>
                            </div>
                            
                        </div>
                        <button type="submit"
                                className="mx-auto w-full px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-custom-orange rounded-lg hover:bg-custom-hover-orange">
                            Je réserve ma place
                        </button>
                    </form>
                       
                    </div>

            
        
                   
                </section>
            </HomeLayout>
        </>
    )
}