import Head from 'next/head'
import React, {useEffect, useState} from "react";
import HomeLayout from "@/components/layouts/Home";
import Link from "next/link";

interface Event {
    name: string;
    description: string;
    id: string;
}


export default function New() {
    const [events, setEvents] = useState<Event[]>([]);

    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
    });

    useEffect(() => {
        fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/event`, {
            method: 'GET',
        })
            .then(response => response.json())
            .then((data) => {
                setEvents(data)

            }).catch((error) => {
            console.log(error);

        });

    }, []);

    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HomeLayout>
                <section>
                    <div className="container my-12 mx-auto px-4 md:px-12">
                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-y-10">
                            {events.map((item, index) => (
                                <Link href={`/event/`} key={index}>
                                    <div className="w-80 bg-white border border-gray-200 rounded-lg shadow mx-auto hover:-translate-y-3 hover:cursor-pointer hover:scale-105 duration-300">
                                    <img className="w-10 mx-auto" src="./home/rocket.svg" alt="crown"/>
                    

                                        <div className="p-5">
                                            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900">{item.name}</h5>

                                            <p className="mb-3 font-normal text-gray-700">{item.description}</p>
                                        </div>
                                    </div>
                                </Link>
                            ))}
                        </div>
                    </div>
                </section>
            </HomeLayout>
        </>
    )
}