import Head from 'next/head'
import AdminLayout from "@/components/layouts/Admin";
import 'flowbite';
import { Grid } from 'gridjs-react';
import "gridjs/dist/theme/mermaid.css";
import { useEffect, useState } from 'react';


export default function Category() {

    const [categories, setCategories] = useState([]);

    useEffect( () => {

        fetch(`http://localhost:3001/category`,{
            method:'GET',
        })
        .then(response => response.json())
        .then( (data) => {
            setCategories(data)
            
        }).catch( (error) =>{
            console.log(error);
            
        });  
    },[]);


    return (
        <>
             <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AdminLayout>
                <div className="p-4 sm:ml-64">
                    <div className="p-4 mt-14">
                
                    <Grid
                        data={categories.map(category => [category.name])}
                        search={true}
                        columns={[
                            {
                                id:'name',
                                name:'Nom'
                            },

                            {
                                id:'action',
                                name:'Actions'
                            },
                        ]}
                        pagination={{
                            limit: 1, 
                        }}

                        language={{
                            'search': {
                                'placeholder': 'Recherche...'
                            },
                        }}
                        />
                    </div>
                </div>
            </AdminLayout>
        </>
    )
}