import Head from 'next/head'
import dynamic from 'next/dynamic'
import {  useEffect } from 'react';

const Chart = dynamic(() => import('react-apexcharts'), { ssr: false });import React, { useState } from 'react';
import AdminLayout from '@/components/layouts/Admin';
import Checkout from '@/components/announcement/Checkout';

export default function Admin() {

    

    const paymentData = [
        { date: '2023-07-01', count: 10 },
        { date: '2023-07-02', count: 5 },
        { date: '2023-07-03', count: 8 },
    ];
    const [options, setOptions] = useState({
        chart: {
            id: "basic-bar"
        },
        xaxis: {
            categories: paymentData.map(data => data.date),
        }
    });

    const [series, setSeries] = useState([
        {
            name: 'Nombre de paiements',
            data: paymentData.map(data => data.count),
        }
    ]);

    useEffect( () => {
    document.body.classList.add("bg-custom-light-blue");
    },[]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AdminLayout>
                <div className="p-4 sm:ml-64">
                    <div className="grid gap-4 xl:grid-cols-2 2xl:grid-cols-3">
                       
                        <div
                            className="p-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                            <div className="flex items-center justify-between mb-4">
                                <div className="flex-shrink-0">
                                    <span
                                        className="text-xl font-bold leading-none text-gray-900 sm:text-2xl dark:text-white">$45,385</span>
                                    <h3 className="text-base font-light text-gray-500 dark:text-gray-400">Sales this
                                        week</h3>
                                </div>
                                <div
                                    className="flex items-center justify-end flex-1 text-base font-medium text-green-500 dark:text-green-400">
                                    12.5%
                                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                                         xmlns="http://www.w3.org/2000/svg">
                                        <path fillRule="evenodd"
                                              d="M5.293 7.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 5.414V17a1 1 0 11-2 0V5.414L6.707 7.707a1 1 0 01-1.414 0z"
                                              clipRule="evenodd"/>
                                    </svg>
                                </div>
                            </div>
                            {(typeof window !== 'undefined') &&

                                <Chart
                                options={options}
                                series={series}
                                type="bar"
                                width="500"
                            />
                            }
                            {/* Card Footer */}
                            <div
                                className="flex items-center justify-between pt-3 mt-4 border-t border-gray-200 sm:pt-6 dark:border-gray-700">
                                <div>
                                    <button
                                        className="inline-flex items-center p-2 text-sm font-medium text-center text-gray-500 rounded-lg hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
                                        type="button" data-dropdown-toggle="weekly-sales-dropdown">Last 7 days <svg
                                        className="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                                              d="M19 9l-7 7-7-7"/>
                                    </svg></button>
                                    {/* Dropdown menu */}
                                    <div
                                        className="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600"
                                        id="weekly-sales-dropdown">
                                        <div className="px-4 py-3" role="none">
                                            <p className="text-sm font-medium text-gray-900 truncate dark:text-white"
                                               role="none">
                                                Sep 16, 2021 - Sep 22, 2021
                                            </p>
                                        </div>
                                        <ul className="py-1" role="none">
                                            <li>
                                                <a href="#"
                                                   className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                                   role="menuitem">Yesterday</a>
                                            </li>
                                            <li>
                                                <a href="#"
                                                   className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                                   role="menuitem">Today</a>
                                            </li>
                                            <li>
                                                <a href="#"
                                                   className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                                   role="menuitem">Last 7 days</a>
                                            </li>
                                            <li>
                                                <a href="#"
                                                   className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                                   role="menuitem">Last 30 days</a>
                                            </li>
                                            <li>
                                                <a href="#"
                                                   className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                                   role="menuitem">Last 90 days</a>
                                            </li>
                                        </ul>
                                        <div className="py-1" role="none">
                                            <a href="#"
                                               className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white"
                                               role="menuitem">Custom...</a>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </AdminLayout>
        </>
    )
}


