import Head from 'next/head'
import HomeLayout from '@/components/layouts/Home'
import Header from '@/components/home/Header'
import Banner from '@/components/home/Banner'
import About from '@/components/home/About'
import Scroll from '@/components/home/scroll/Scroll';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomeLayout>
                <Header/>
                <Scroll />
                <About/>
                <Banner/>
            </HomeLayout>
        </>
)
}
