import Head from 'next/head'
import HomeLayout from '@/components/layouts/Home'
import Header from '@/components/home/Header'
import Banner from '@/components/home/Banner'
import About from '@/components/home/About'
import Scroll from '@/components/home/scroll/Scroll';
import {useEffect} from "react";

export default function Home() {
    useEffect(() =>
    {
        document.body.classList.add("bg-custom-light-orange");
    });

    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomeLayout>
                <Header/>
                <Scroll />
                <About/>
                <Banner/>
            </HomeLayout>
        </>
)
}
