import Head from 'next/head'
import React, { useEffect, useRef, useState } from "react";
import HomeLayout from "@/components/layouts/Home";
import Link from "next/link";
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react';
import Loader from "@/components/utils/Loader";

interface User {
    name: string;
    firstname?:string;
    email:string;
    balance?:number
    points:number
    role:string;
}

export default function Profil() {

    const supabase = useSupabaseClient()
    const [user,setUser]= useState<User>();

    const [loader, setLoader] = useState(false);

    useEffect(() =>
    {
        document.body.classList.add("bg-custom-light-orange");

        const fetchData = async () => {
            setLoader(true)
            const {data: {session}} = await supabase.auth.getSession();
            fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/me`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Bearer ' + session?.access_token
                }
            })
                .then(response => response.json())
                .then((data) => {

                    setUser(data[0]);
                    setLoader(false);
                   
                }).catch((error) => {
                console.log(error);
            });
            
        }

    

        fetchData();
     
    
    },[]);

    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeLayout>
                <section>

                {
                    !loader && user ? (
                
                    <div>
                        <div className="w-full">
                            <div className="flex flex-col">
                            </div>
                            <div className="w-full">
                            <div className="flex flex-col">
                                <div className="bg-white border border-white shadow rounded p-4 m-4">
                                    <div className="flex-none sm:flex">
                                        <div className=" relative h-32 w-32   sm:mb-0 mb-3">

                                        { 
                                            user?.points >= 100 && user?.points < 500 && <img src="./creature1.svg" alt="logo"/>
                                        }

                                        { 
                                            user?.points >= 500 && user?.points < 1000 &&  <img src="./creature2.svg" alt="logo"/>
                                        }

                                        { 
                                            user?.points >= 1000 && user?.points < 2000 && <img src="./creature3.svg" alt="logo"/>
                                        }
                                        { 
                                            user?.points >= 2000 && <img src="./otter.png" alt="logo"/>
                                        }
                                        
                                        </div>
                                        <div className="flex-auto sm:ml-5 justify-evenly">
                                            <div className="flex items-center justify-between sm:mt-2">
                                                <div className="flex items-center">
                                                    <div className="flex flex-col">
                                                        <div className="w-full flex-none text-lg text-gray-800 font-bold leading-none">{user?.firstname} {user?.name}</div>
                                                        <div className="flex-auto text-gray-500 my-1">
                                                            <span className="mr-3 ">{user?.email}</span><span className="mr-3 border-r border-gray-200  max-h-0"></span>

                                                            { user?.balance ? (
                                                                <span>{user?.balance} €</span>
                                                            ) : ""
                                                            
                                                            }
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="flex flex-row items-center">
                                            <div className="flex-1 inline-flex  hidden items-center">
                                                    </div>
                                                </div>
                                                <div className="flex pt-2 text-sm text-gray-500">
                                                    <div className="flex-1 inline-flex items-center">

                                                        {
                                                            user.points ? (
                                                                <p className="">{user?.points} points</p>
                                                            ) : ""
                                                        }
                                                    
                                                       
                                                       
                                                    
                                                    </div>
                                                    <Link href="/updateProfil"><button  className="text-custom-dark bg-custom-white border-2 border-custom-pastel-purple hover:bg-custom-pastel-purple hover:text-black focus:outline-none font-bold rounded-lg text-sm py-2 px-4 md:py-2 text-center mr-0">Modifier le profil</button></Link>
                                                    
                                                </div>
                                            </div>

                                            
                                        </div>
                                        <div className="flex gap-5">

                                        { 
                                            user?.points >= 100 && 
                                            <>

                                            <div className="">
                                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center border-grey-light`}>
                                                    <span className="text-grey-darker text-center w-full">
                                                    <img src="./creature1.svg" alt="logo"/>
                                                    </span>
                                                </div>
                                            </div>
                                            </>
                                        }

                                        { 
                                            user?.points >= 500 && 
                                            <>

                                            <div className="">
                                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center border-grey-light`}>
                                                    <span className="text-grey-darker text-center w-full">
                                                    <img src="./creature2.svg" alt="logo"/>
                                                    </span>
                                                </div>
                                            </div>
                                            </>
                                        }

                                        { 
                                            user?.points >= 1000 && 
                                            <>

                                            <div className="">
                                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center border-grey-light`}>
                                                    <span className="text-grey-darker text-center w-full">
                                                    <img src="./creature3.svg" alt="logo"/>
                                                    </span>
                                                </div>
                                            </div>
                                            </>
                                        }
                                        { 
                                            user?.points >= 2000 && 
                                            <>

                                            <div className="">
                                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center border-grey-light`}>
                                                    <span className="text-grey-darker text-center w-full">
                                                    <img src="./otter.png" alt="logo"/>
                                                    </span>
                                                </div>
                                            </div>
                                            </>
                                        }

                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                       
                        {  user.role == "CLIENT" ? (
                        <div className="max-w-xl mx-auto my-4 pb-4">	
                            <div className="flex pb-3">
                                <div className="flex-1">
                                </div>

                                <div className="flex-1">
                                    <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center ${ user && user.points >=100 ? 'border-custom-pastel-purple':'border-grey-light' }`}>
                                        <span className="text-grey-darker text-center w-full">
                                            <img src="./creature1.svg" alt="logo"/>
                                        </span>
                                    </div>
                                </div>


                                <div className="w-1/6 align-center items-center align-middle content-center flex">
                                    <div className="w-full bg-gray-200 rounded items-center align-middle align-center flex-1">
                                        <div className={`bg-custom-pastel-purple text-xs leading-none py-1 text-center text-grey-darkest rounded`} style={user && user.points > 100 ? { width: user.points < 500 ? ((user?.points / 500) * 100) + "%" : "100%" } : { width: '0' }}></div>
                                    </div>
                                </div>
                            
                                
                                <div className="flex-1">
                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center ${ user && user.points >=500 ? 'border-custom-pastel-purple':'border-grey-light' }`}>
                                        <span className="text-grey-darker text-center w-full">
                                        <img src="./creature2.svg" alt="logo"/>
                                        </span>
                                    </div>
                                </div>
                            
                                <div className="w-1/6 align-center items-center align-middle content-center flex">
                                    <div className="w-full bg-gray-200 rounded items-center align-middle align-center flex-1">
                                        <div className="bg-custom-pastel-purple text-xs leading-none py-1 text-center text-grey-darkest rounded " style={user && user.points > 500 ? { width: user.points < 1000 ? (( (user?.points - 500) / 500 ) * 100) + "%" : "100%" } : { width: '0' }}></div>
                                    </div>
                                </div>
                            
                                <div className="flex-1">
                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center ${ user && user.points >=1000 ? 'border-custom-pastel-purple':'border-grey-light' }`}>
                                        <span className="text-grey-darker text-center w-full">
                                        <img src="./creature3.svg" alt="logo"/>
                                        </span>
                                    </div>
                                </div>
                            
                            
                                <div className="w-1/6 align-center items-center align-middle content-center flex">
                                    <div className="w-full bg-gray-200 rounded items-center align-middle align-center flex-1">
                                        <div className="bg-custom-pastel-purple text-xs leading-none py-1 text-center text-grey-darkest rounded "  style={user && user.points > 1000 ? { width: user.points < 2000 ? (( (user?.points - 1000) / 1000 ) * 100) + "%" : "100%" } : { width: '0' }}></div>
                                    </div>
                                </div>


                                <div className="flex-1">
                                <div className={`w-10 h-10 bg-white border-2 mx-auto rounded-full text-lg text-white flex items-center ${ user && user.points >=2000 ? 'border-custom-pastel-purple':'border-grey-light' }`}>
                                        <span className="text-grey-darker text-center w-full"><img src="./otter.png" alt="logo"/></span>
                                    </div>
                                </div>
                            
                            
                                <div className="flex-1">
                                </div>		
                            </div>
                            
                            <div className="flex text-xs content-center text-center">
                                <div className="w-1/4">
                                    100 points
                                </div>
                                
                                <div className="w-1/4">
                                    500 points
                                </div>
                                
                                <div className="w-1/4">
                                    1000 points
                                </div>
                                
                                <div className="w-1/4">
                                    2000 points
                                </div>			
                            </div>
                        </div>

                        ) : ""}
                        </div>






                    ): <Loader></Loader>
                    }
                </section>
            </HomeLayout>
        </>
    )
}

