import Head from 'next/head'
import HomeLayout from '@/components/layouts/Home'
import {useEffect} from "react";
import UpdateProfil from '@/components/profil/UpdateUser'

export default function Home() {
    useEffect(() =>
    {
        document.body.classList.add("bg-custom-light-orange");
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomeLayout>
               <UpdateProfil/>
            </HomeLayout>
        </>
)
}
