import React, {Fragment, useEffect, useRef, useState} from "react";
import HomeLayout from "@/components/layouts/Home";
import Head from 'next/head'
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Conversation from "@/components/message/Conversation";


export default function Message(){

    interface Party{
        name: string;
        id: string;
    }

    const supabaseClient = useSupabaseClient();
    const [parties,setParties] = useState([]);
    const [party,setParty] = useState<string>("");


    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
    },[]);



    useEffect(() => {

        fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/party/partiesByMessage`, {
            method: 'GET',
        })
            .then(response => response.json())
            .then((data) => {
               setParties(data)
            }).catch((error) => {
            console.log(error);
        });
        
    },[]);
   


    return (
        <Fragment>
             <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HomeLayout>

            <div className="flex h-screen antialiased text-gray-800">
                <div className="flex flex-row h-full w-full overflow-x-hidden">
                <div className="flex flex-col py-8 pl-6 pr-2 rounded w-64 flex-shrink-0 ">
                
                    <div className="flex flex-col mt-8">
                    <div className="flex flex-row items-center justify-between text-xs">
                        <span className="font-bold">Annonces</span>
                    </div>
                    
                    <div className="flex flex-row items-center justify-between text-xs mt-6">
                        <span className="font-bold">Soirées</span>
                        
                    </div>
                    
                    <div className="flex flex-col space-y-1 mt-4 -mx-2 h-48 overflow-y-auto">
                        {
                            parties.map((party:Party, index) => (
                                <button onClick={ () => setParty(party.id)} key={index} className="flex flex-row items-center hover:bg-custom-pastel-purple rounded-xl p-2">
                                    <div className="ml-2 text-sm font-semibold">{party.name}</div>
                                </button>
                            ))
                        }
                    
                    </div>
                    </div>
                </div>

                <Conversation party={party} />
              </div>
            </div>
                
            </HomeLayout>
        </Fragment>
    );

}