import Head from 'next/head'
import HomeLayout from '@/components/layouts/Home'
import {useEffect} from "react";
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'

export default function Home() {
    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
    }, []);

    return (
        <>
            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomeLayout>
                <section>
                    <div className="container">
                        <div className="w-full flex justify-center">
                            <div className="w-3/4 mt-10">
                                <FullCalendar
                                    plugins={[dayGridPlugin]}
                                    initialView="dayGridMonth"
                                    firstDay={1}
                                    locale="fr"
                                    headerToolbar={{
                                        center: 'title',
                                        left: '',
                                    }}
                                    buttonText={{
                                        today: 'Aujourd\'hui',
                                    }}
                                    events={[
                                        {title: 'event 1', date: '2023-07-01'},
                                        {title: 'event 2', date: '2023-07-02'}
                                    ]
                                    }
                                />
                            </div>
                        </div>
                    </div>
                </section>
            </HomeLayout>
        </>
)
}