import HomeLayout from "@/components/layouts/Home";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import Head from "next/head";
import Link from "next/link";
import React, {useEffect, useState} from "react";


export default function Meeting() {

    interface CheckoutVisio{
        id:string;
        visio:Visio;
    }

    interface Visio{
        id:string;
        date:string;
        startTime:string;
        endTime:string
        profiles:User
    }
    interface User {
        firstname:string;
        name:string;
    }

    const supabase = useSupabaseClient();
    const [isLoader, setIsLoader] = useState<boolean>(false);
    const [isLoad, setIsLoad] = useState<boolean>(true);
    const [load, setLoad] = useState<boolean>(false)
    const [meetings, setMeetings] = useState([])

    const fetchData = async () => {
        const {data: {session}} = await supabase.auth.getSession();

        fetch(`${process.env.NEXT_PUBLIC_CLIENT_API}/visio/getMyMeetings`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer ' + session?.access_token,
            },
        })
            .then(response => response.json())
            .then((data) => {
                setMeetings(data);
                console.log(data);
                setIsLoad(false);
            }).catch((error) => {
            console.log(error);
        });
    }

    useEffect(() => {
        document.body.classList.add("bg-custom-light-orange");
        fetchData()
      
    }, []);


    return (
        <>

            <Head>
                <title>Ludotter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HomeLayout>
                <h2 className="mt-10 mb-3 ml-5 text-3xl font-semibold text-center">Mes réunions</h2>

                {
                    meetings.length > 0 && meetings.map((item: CheckoutVisio, index) => (
                        <div className="w-full" key={index}>
                            <div className="flex flex-col">
                                <div className="bg-white border border-white shadow rounded p-4 m-4">
                                    <div className="flex justify-between">
                                        <div>
                                            <div className="flex-none sm:flex font-medium text-xl">{item.visio.profiles.firstname} {item.visio.profiles.name}</div>
                                            <div className="flex-none sm:flex text-xs">{item.visio.date}</div>
                                            <div className="flex-none sm:flex text-xs">{item.visio.startTime} {item.visio.endTime}</div>
                                        </div>
                                        <div>
                                            <Link href={`/meet/${item.visio.id}`} className="mx-2 px-5 py-2.5 text-sm font-medium text-white bg-custom-orange rounded-lg hover:bg-custom-hover-orange">
                                                    Rejoindre
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )
                    )
                }
                
            </HomeLayout>
        </>
    );
}