apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: rexrider/ludotter:$IMAGE_TAG
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  type: NodePort
  selector:
    app: message
  ports:
    - name: message
      port: 4010
      targetPort: 4010